site_name: Sami Barchid
theme:
  name: material
  palette:
    scheme: youtube
    primary: "#d35400"
  font:
    text: Montserrat
  logo: coffee.svg
markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
extra_css:
  - stylesheets/extra.css
plugins:
  - search
extra:
  social:
    - icon: fontawesome/brands/twitter 
      link: https://twitter.com/BarchidSami
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/sami-barchid/
    - icon: fontawesome/brands/github
      link: https://github.com/Barchid
